Repository DxChainNetwork/godx, pull requests merged in 2019-10, with the labels that each got.

#204 DPOS formatting fix and privateDebugAPI fix
  core/block_validator.go
  core/blockchain.go
  core/evm.go
  core/rawdb/accessors_chain.go
  eth/api.go
  eth/api_tracer.go
  rpc/client.go
Labels: bug

#205 Windows fix
  cmd/gdx/consolecmd.go
  common/json_test.go
  common/testdata/windows/corrupted.json
  common/testdata/windows/corrupted.json_temp
  common/testdata/windows/manual.json
  common/testdata/windows/manual.json_temp
  common/testdata/windows/persist.json
  common/testdata/windows/persist.json_temp
  common/testdata/windows/test.json
  common/testdata/windows/test.json_temp
  storage/dxpath.go
  storage/dxpath_test.go
  storage/storageclient/filesystem/api_test.go
  storage/storageclient/filesystem/dirmetadataupdate.go
  storage/storageclient/filesystem/dirmetadataupdate_test.go
  storage/storageclient/filesystem/filesystem.go
  storage/storageclient/filesystem/filesystem_test.go
  storage/storageclient/filesystem/generate.go
  storage/storageclient/uploadheap.go
  storage/storagehost/storagemanager/addsector_test.go
  storage/storagehost/storagemanager/addstoragefolder_test.go
  storage/storagehost/storagemanager/expandfolder.go
  storage/storagehost/storagemanager/expandfolder_test.go
Labels: bug, enhancement

#206 Arm-7 Overflow Bug Fix
  storage/storageclient/storagehostmanager/scan.go
Labels: bug

#209 fix the issue of cannot attach to macos when specifying datadir
  cmd/gdx/consolecmd.go
Labels: bug

#208 Discovery Protocol Hot Fix
  p2p/discover/udp.go
Labels: bug

#212 Release0.9.1
  LINUX.md
  README.md
  TUTORIAL.md
  WINDOWS.md
  params/version.go
Labels: Documentation

#207 Example: trie is a content based storage system
  trie/trie_example_test.go
Labels: Documentation
